import type { Benjamin, Technology, Project } from "../global";

const technologies = [
    // Frontend Technologies
    {
        key: 0,
        name: "HTML5",
        image: "logos/html5.svg",
        link: "https://html.spec.whatwg.org/",
        type: "Frontend",
        isLearning: false,
    },
    {
        key: 1,
        name: "Javascript",
        image: "logos/js.svg",
        link: "https://www.ecma-international.org/publications-and-standards/standards/ecma-262/",
        type: "Frontend",
        isLearning: false,
    },
    {
        key: 2,
        name: "Typescript",
        image: "logos/typescript.svg",
        link: "https://www.typescriptlang.org/",
        type: "Frontend",
        isLearning: false,
    },
    {
        key: 3,
        name: "React",
        image: "logos/react.svg",
        link: "https://react.dev/",
        type: "Frontend",
        isLearning: false,
    },
    {
        key: 4,
        name: "Next.js",
        image: "logos/nextjs.svg",
        link: "https://nextjs.org/",
        type: "Frontend",
        isLearning: false,
    },
    {
        key: 5,
        name: "Vue.JS",
        image: "logos/vue.svg",
        link: "https://vuejs.org/",
        type: "Frontend",
        isLearning: true,
    },
    {
        key: 6,
        name: "Angular",
        image: "logos/angular.svg",
        link: "https://angular.io/",
        type: "Frontend",
        isLearning: true,
    },
    {
        key: 7,
        name: "Svelte",
        image: "logos/svelte.png",
        link: "https://svelte.dev/",
        type: "Frontend",
        isLearning: true,
    },
    {
        key: 8,
        name: "SolidJS",
        image: "logos/solid.svg",
        link: "https://www.solidjs.com/",
        type: "Frontend",
        isLearning: true,
    },
    {
        key: 9,
        name: "RedwoodJS",
        image: "logos/redwood.svg",
        link: "https://redwoodjs.com/",
        type: "Frontend",
        isLearning: true,
    },
    {
        key: 10,
        name: "Redux",
        image: "logos/redux.svg",
        link: "https://redux.js.org/",
        type: "Frontend",
        isLearning: true,
    },
    {
        key: 11,
        name: "Webpack",
        image: "logos/webpack.png",
        link: "https://webpack.js.org/",
        type: "Frontend",
        isLearning: false,
    },
    {
        key: 12,
        name: "Astro",
        image: "logos/astro.svg",
        link: "https://astro.build/",
        type: "Frontend",
        isLearning: true,
    },
    {
        key: 13,
        name: "Zustand",
        image: "logos/zustand.svg",
        link: "https://github.com/pmndrs/zustand",
        type: "Frontend",
        isLearning: false,
    },
    {
        key: 30,
        name: "CSS3",
        image: "logos/css3.svg",
        link: "https://www.w3.org/TR/CSS/#css",
        type: "Frontend",
        isLearning: false,
    },
    {
        key: 31,
        name: "SASS",
        image: "logos/sass.svg",
        link: "https://sass-lang.com/",
        type: "Frontend",
        isLearning: false,
    },
    {
        key: 32,
        name: "tailwindcss",
        image: "logos/tailwind.svg",
        link: "https://tailwindcss.com/",
        type: "Frontend",
        isLearning: false,
    },

    {
        key: 33,
        name: "Bootstrap",
        image: "logos/bootstrap.png",
        link: "https://getbootstrap.com/",
        type: "Frontend",
        isLearning: false,
    },
    {
        key: 34,
        name: "Material-UI",
        image: "logos/materialui.svg",
        link: "https://material-ui.com/",
        type: "Frontend",
        isLearning: false,
    },
    {
        key: 35,
        name: "Chakra UI",
        image: "logos/chakra.svg",
        link: "https://chakra-ui.com",
        type: "Frontend",
        isLearning: false,
    },
    {
        key: 36,
        name: "DaisyUI",
        image: "logos/daisyui.png",
        link: "https://daisyui.com/",
        type: "Frontend",
        isLearning: false,
    },
    {
        key: 37,
        name: "shadcn",
        image: "logos/shadcn.png",
        link: "https://ui.shadcn.com/",
        type: "Frontend",
        isLearning: false,
    },
    {
        key: 38,
        name: "Mantine",
        image: "logos/mantine.svg",
        link: "https://mantine.dev/",
        type: "Frontend",
        isLearning: false,
    },

    // Backend Technologies
    {
        key: 50,
        name: "Node.js",
        image: "logos/nodejs.png",
        link: "https://nodejs.org/",
        type: "Backend",
        isLearning: false,
    },
    {
        key: 51,
        name: "Express",
        image: "logos/expressjs.png",
        link: "https://expressjs.com/",
        type: "Backend",
        isLearning: false,
    },
    {
        key: 56,
        name: "Python",
        image: "logos/python.svg",
        link: "https://www.python.org/",
        type: "Backend",
        isLearning: true,
    },
    {
        key: 57,
        name: "Redis",
        image: "logos/redis.png",
        link: "https://redis.io/",
        type: "Backend",
        isLearning: true,
    },
    {
        key: 58,
        name: "GraphQL",
        image: "logos/graphql.png",
        link: "https://graphql.org/",
        type: "Backend",
        isLearning: true,
    },
    {
        key: 59,
        name: "Socket.io",
        image: "logos/socket.svg",
        link: "https://socket.io/",
        type: "Backend",
        isLearning: true,
    },
    {
        key: 60,
        name: "Deno",
        image: "logos/deno.svg",
        link: "https://deno.com/",
        type: "Backend",
        isLearning: true,
    },
    {
        key: 61,
        name: "Bun",
        image: "logos/bun.svg",
        link: "https://bun.sh/",
        type: "Backend",
        isLearning: true,
    },
    {
        key: 62,
        name: "NestJS",
        image: "logos/nestjs.svg",
        link: "https://nestjs.com/",
        type: "Backend",
        isLearning: true,
    },
    {
        key: 63,
        name: "Go",
        image: "logos/go.svg",
        link: "https://golang.org/",
        type: "Backend",
        isLearning: true,
    },
    {
        key: 64,
        name: "PHP",
        image: "logos/PHP.png",
        link: "https://www.php.net/",
        type: "Backend",
        isLearning: false,
    },
    {
        key: 65,
        name: "Apache",
        image: "logos/apache.png",
        link: "https://httpd.apache.org/",
        type: "Backend",
        isLearning: false,
    },
    {
        key: 66,
        name: "XAMPP",
        image: "logos/xampp.svg",
        link: "https://www.apachefriends.org/index.html",
        type: "Backend",
        isLearning: false,
    },
    {
        key: 67,
        name: "Laravel",
        image: "logos/laravel.svg",
        link: "https://laravel.com/",
        type: "Backend",
        isLearning: true,
    },
    {
        key: 68,
        name: "Convex",
        image: "logos/convex.svg",
        link: "https://www.convex.dev/",
        type: "Backend",
        isLearning: false,
    },

    // Databases
    {
        key: 52,
        name: "MongoDB",
        image: "logos/mongodb.svg",
        link: "https://www.mongodb.com/",
        type: "Database",
        isLearning: false,
    },
    {
        key: 53,
        name: "Mongoose",
        image: "logos/mongoose.png",
        link: "https://www.mongoosejs.com/",
        type: "Database",
        isLearning: false,
    },
    {
        key: 54,
        name: "Prisma",
        image: "logos/prisma.svg",
        link: "https://www.prisma.io/",
        type: "Database",
        isLearning: false,
    },
    {
        key: 55,
        name: "PostgreSQL",
        image: "logos/postgresql.svg",
        link: "https://www.postgresql.org/",
        type: "Database",
        isLearning: false,
    },
    {
        key: 68,
        name: "mySQL",
        image: "logos/mysql.png",
        link: "https://www.mysql.com/",
        type: "Database",
        isLearning: false,
    },

    // Tools
    {
        key: 70,
        name: "Storybook",
        image: "logos/storybook.png",
        link: "https://storybook.js.org/",
        type: "Tool",
        isLearning: true,
    },
    {
        key: 71,
        name: "Figma",
        image: "logos/figma.svg",
        link: "https://www.figma.com",
        type: "Tool",
        isLearning: false,
    },
    {
        key: 72,
        name: "VSCode",
        image: "logos/vscode.svg",
        link: "https://code.visualstudio.com/",
        type: "Tool",
        isLearning: false,
    },
    {
        key: 73,
        name: "Vite",
        image: "logos/vite.svg",
        link: "https://vitejs.dev/",
        type: "Tool",
        isLearning: false,
    },
    {
        key: 74,
        name: "GitHub Copilot",
        image: "logos/copilot.png",
        link: "https://github.com/features/copilot",
        type: "Tool",
        isLearning: false,
    },
    {
        key: 75,
        name: "ChatGPT",
        image: "logos/ChatGPT_logo.svg.png",
        link: "https://chat.openai.com/",
        type: "Tool",
        isLearning: false,
    },
    {
        key: 76,
        name: "Stripe",
        image: "logos/stripe.png",
        link: "https://www.stripe.com/",
        type: "Tool",
        isLearning: false,
    },

    // CI/CD
    {
        key: 80,
        name: "Jest",
        image: "logos/jest.svg",
        link: "https://jestjs.io/",
        type: "CI/CD",
        isLearning: false,
    },
    {
        key: 81,
        name: "React Testing Library",
        image: "logos/rtl.png",
        link: "https://testing-library.com/docs/react-testing-library/intro/",
        type: "CI/CD",
        isLearning: false,
    },
    {
        key: 82,
        name: "Playwright",
        image: "logos/playwright.svg",
        link: "https://playwright.dev/",
        type: "CI/CD",
        isLearning: false,
    },
    {
        key: 83,
        name: "Cypress",
        image: "logos/cypress.svg",
        link: "https://www.cypress.io/",
        type: "CI/CD",
        isLearning: true,
    },
    {
        key: 84,
        name: "Husky",
        image: "logos/husky.svg",
        link: "https://typicode.github.io/husky/#/",
        type: "CI/CD",
        isLearning: false,
    },
    {
        key: 85,
        name: "GitHub",
        image: "logos/github.svg",
        link: "https://github.com/benjamindotdev",
        type: "CI/CD",
        isLearning: false,
    },
    {
        key: 86,
        name: "Docker",
        image: "logos/docker.svg",
        link: "https://www.docker.com/",
        type: "CI/CD",
        isLearning: true,
    },
    {
        key: 87,
        name: "Vercel",
        image: "logos/vercel.svg",
        link: "https://vercel.com/",
        type: "CI/CD",
        isLearning: false,
    },
    {
        key: 88,
        name: "Netlify",
        image: "logos/netlify.png",
        link: "https://www.netlify.com/",
        type: "CI/CD",
        isLearning: false,
    },
    {
        key: 89,
        name: "Railway",
        image: "logos/railway.svg",
        link: "https://www.railway.app/",
        type: "CI/CD",
        isLearning: false,
    },
    {
        key: 90,
        name: "Heroku",
        image: "logos/heroku.svg",
        link: "https://www.heroku.com/",
        type: "CI/CD",
        isLearning: false,
    },

    // Mobile Technologies
    {
        key: 100,
        name: "React Native",
        image: "logos/reactnative.svg",
        link: "https://reactnative.dev/",
        type: "Mobile",
        isLearning: true,
    },
    {
        key: 101,
        name: "Expo",
        image: "logos/expo.png",
        link: "https://expo.dev/",
        type: "Mobile",
        isLearning: true,
    },

    // Project Management
    {
        key: 110,
        name: "Notion",
        image: "logos/notion.svg",
        link: "https://www.notion.so/",
        type: "Project Management",
        isLearning: false,
    },
    {
        key: 111,
        name: "Trello",
        image: "logos/trello.svg",
        link: "https://www.trello.com/",
        type: "Project Management",
        isLearning: false,
    },
    {
        key: 112,
        name: "Slack",
        image: "logos/slack.svg",
        link: "https://www.slack.com/",
        type: "Project Management",
        isLearning: false,
    },
    {
        key: 113,
        name: "Taiga",
        image: "logos/taiga.png",
        link: "https://www.taiga.io/",
        type: "Project Management",
        isLearning: false,
    },

    // Content Management
    {
        key: 120,
        name: "Wordpress",
        image: "logos/wordpress.png",
        link: "https://www.wordpress.com/",
        type: "Content Management",
        isLearning: false,
    },
    {
        key: 121,
        name: "Shopify",
        image: "logos/shopify.svg",
        link: "https://www.shopify.com/",
        type: "Content Management",
        isLearning: false,
    },

    // Cloud Technologies
    {
        key: 130,
        name: "AWS",
        image: "logos/aws.png",
        link: "https://aws.amazon.com/",
        type: "Cloud",
        isLearning: false,
    },
    {
        key: 131,
        name: "Azure",
        image: "logos/azure.png",
        link: "https://azure.microsoft.com/",
        type: "Cloud",
        isLearning: true,
    },
    {
        key: 132,
        name: "Google Cloud",
        image: "logos/googlecloud.png",
        link: "https://cloud.google.com/",
        type: "Cloud",
        isLearning: true,
    },
] as Technology[];

const projects = [
    {
        key: 0,
        name: "solitairedaily.com",
        image: "logos/solitaire.png",
        description: "A modern take on the classic solitaire games.",
        status: "completed",
        type: "freelance",
        techStack: [
            "Next.js",
            "tailwindcss",
            "Convex",
            "Vercel"
        ],
        deployedLink: "https://solitairedaily.com",
        repoLink: "https://github.com/benjamindotdev/solitairedaily",
        client: {
            name: "SolitaireDaily",
        },
    },
    {
        key: 1,
        name: "sh.coach",
        image: "logos/shcoach.svg",
        description: "Leadership coaching portfolio for Stephanie Herre. Modern responsive site with custom layouts and interactive features.",
        status: "completed",
        type: "freelance",
        techStack: [
            "React",
            "Typescript",
            "Vite",
            "tailwindcss",
            "React Router",
            "Netlify"
        ],
        deployedLink: "https://sh.coach",
        repoLink: "https://github.com/benjamindotdev/sh",
        client: {
            name: "Stephanie Herre",
            linkedIn: "https://www.linkedin.com/in/stephanie-herre/",
            position: "Leadership Coach & Consultant",
            testimonial: "Benjamin delivered a beautiful, performant website that perfectly captures my coaching brand. His attention to detail and technical expertise made the process smooth and enjoyable.",
        },
    },
    {
        key: 2,
        name: "Storytime",
        image: "logos/storytime.png",
        description: "AI generated bedtime stories for kids.",
        status: "completed",
        techStack: [
            "Typescript",
            "Next.js",
            "tailwindcss",
            "ChatGPT",
            "Prisma",
            "MongoDB",
            "Vercel",
        ],
        deployedLink: "https://storytime-by-benjamindotdev.vercel.app",
        repoLink: "https://github.com/benjamindotdev/storytime",
    },
    {
        key: 3,
        name: "Frosch",
        image: "logos/Frosch.gif",
        description: "A web-game where you help a frog cross different terrain.",
        status: "completed",
        techStack: ["HTML5", "CSS3", "Javascript", "Webpack", "Netlify"],
        deployedLink: "https://playfrosch.netlify.app",
        repoLink: "https://github.com/benjamindotdev/frosch",
    },
    {
        key: 4,
        name: "littlelemon",
        image: "logos/littlelemon.svg",
        description: "Final project for the Meta Frontend Developer course.",
        status: "completed",
        techStack: [
            "React",
            "CSS3",
            "Typescript",
            "Chakra UI",
            "Stripe",
            "Jest",
            "React Testing Library",
            "Netlify",
        ],
        deployedLink: "https://littlelemonbybenjamin.netlify.app/",
        repoLink: "https://github.com/benjamindotdev/LittleLemon",
    }
] as Project[];


const benjamin = {
    name: "Benjamin",
    hero: "images/hero.webp",
    about: [
        {
            key: 0,
            image: "images/coachBenWithTeam.webp",
            text: "After growing up in London 🇬🇧, I spent a decade as a youth football coach in New Jersey, USA. I mentored players on and off the pitch—building resilience, teamwork, and confidence. Trophies were nice, but the real wins were the long-term relationships with players and their families. That experience shaped how I lead teams and communicate under pressure."
        },
        {
            key: 1,
            image: "images/hackshow.webp",
            text: "After moving to Berlin 🇩🇪, I completed the Ironhack Web Development bootcamp in Berlin and won the Hackshow with my final project. I was then invited back as the Teaching Assistant for the course I just finished, where I taught solo, ran code reviews, and helped debug full-stack projects—sharpening my own skills while helping others level up."
        },
        {
            key: 2,
            image: "images/dadWithMiles.webp",
            text: "Today I’m the sole developer at Shep, working directly alongside the two founders of this early-stage startup. With no dedicated tech team yet, I own the entire stack—from prototyping features to deploying production code—while helping shape the product vision and technical direction from the ground up. It’s fast, hands-on, and every line of code directly impacts the company’s future."

        }
    ],
    contacts: [
        {
            key: 0,
            name: "email",
            link: "mailto:hello@benjamin.dev",
            icon: "icons/email.svg",
        }
    ],
    socials: [
        {
            key: 0,
            name: "LinkedIn",
            image: "logos/linkedin.svg",
            link: "https://www.linkedin.com/in/benjamin-elliott-163280280/",
        },
        {
            key: 1,
            name: "Github",
            image: "logos/github.svg",
            link: "https://github.com/benjamindotdev",
        }
    ],
    experience: [
        {
            key: 0,
            title: "Teaching Assistant",
            company: "Ironhack",
            location: "Berlin, Germany",
            date: "September 2024 - December 2024",
            description:
                "Tech bootcamp providing 12 week programs for web dev, UX / UI and data science",
            details: [
                {
                    key: 0,
                    text: "Teaching lesson content in shifts with the lead teacher",
                },
                {
                    key: 1,
                    text: "Guiding students through the curriculum, providing feedback and support",
                },
                {
                    key: 2,
                    text: "Solving technical issues, giving career advice, being approachable and helpful.",
                },
            ],
            techStack: [
                "HTML5",
                "CSS3",
                "Javascript",
                "React",
                "Typescript",
                "Next.js",
                "tailwindcss",
                "shadcn",
                "Node.js",
                "Express",
                "Mongoose",
                "MongoDB",
                "Vercel",
                "Railway",
                "Jest",
                "React Testing Library",
                "Taiga",
            ],
            link: "www.ironhack.com/de-en",
            logo: "logos/Ironhack_idvM-wR3Mf_6.svg",
            type: "Full-time",
            isCurrent: false,
        },
        {
            key: 1,
            title: "Web Development Intern",
            company: "OrganicsBest",
            location: "Berlin, Germany",
            date: "January 2025",
            description:
                "An e-commerce platform for organic baby food, providing a range of products",
            details: [
                {
                    key: 0,
                    text: "Working in a team to develop and maintain the frontend of the website",
                },
                {
                    key: 1,
                    text: "Improving the page load speed and performance",
                },
                {
                    key: 2,
                    text: "Collaborating with the backend team to integrate APIs and ensure smooth data flow",
                },
            ],
            techStack: [
                "HTML5",
                "CSS3",
                "Javascript",
                "Webpack",
                "Wordpress",
                "Shopify",
            ],
            link: "www.organicsbestshop.com",
            logo: "logos/organicsbest.webp",
            type: "Internship",
            isCurrent: false,
        },
        {
            key: 4,
            title: "Full Stack Web Developer",
            company: "Genie TechBio",
            location: "Berlin, Germany",
            date: "April 2025 - June 2025",
            description:
                "AI-powered bioinformatician, that creates plots and tables for user data visualization",
            details: [
                {
                    key: 0,
                    text: "Redesigning the frontend to comply with UX/UI principles and best practices",
                },
                {
                    key: 1,
                    text: "Implementing Zustand for better state management across components",
                },
                {
                    key: 2,
                    text: "Creating RESTful API architecture for improved data flow and security",
                },
            ],
            techStack: [
                "Typescript",
                "React",
                "tailwindcss",
                "Zustand",
                "Material-UI",
                "Python",
                "PostgreSQL",
                "AWS"
            ],
            link: "www.genietechbio.com",
            logo: "logos/genie.jpeg",
            type: "Full-time",
            isCurrent: false,
        },
        {
            key: 6,
            title: "Full Stack Web Developer",
            company: "Shep",
            location: "Berlin, Germany",
            date: "July 2025 - Present",
            description:
                "AI-powered financial dashboard, allowing visibility across other tools and services",
            details: [
                {
                    key: 0,
                    text: "Building the MVP from the ground up with cutting–edge industry tools",
                },
                {
                    key: 1,
                    text: "Dealing with handling state from multiple different APIs at the same time",
                },
                {
                    key: 2,
                    text: "Being the technical lead to implement product requirements and deliverables",
                },
            ],
            techStack: [
                "Next.js",
                "Typescript",
                "tailwindcss",
                "shadcn",
                "Convex",
            ]
            ,
            link: "https://www.shephq.com/",
            logo: "logos/shep.png",
            type: "Full-time",
            isCurrent: true,

        }
    ],
    links: [
        {
            key: 0,
            title: "About",
            route: "/about",
        },
        {
            key: 1,
            title: "Experience",
            route: "/experience",
        },
        {
            key: 2,
            title: "Freelance",
            route: "/freelance",
        },
        {
            key: 3,
            title: "Projects",
            route: "/projects",
        },
        {
            key: 4,
            title: "Certifications",
            route: "/certifications",
        },
    ],
    certifications: [
        {
            key: 0,
            name: "Web Development Bootcamp (full-time)",
            logo: "logos/Ironhack_idVsNwhECC_4.svg",
            description:
                "Completed in September 2024. Won hackshow with asozial.dev. Offered a position as a TA afterwards, due to my passion and willingness to help my colleagues.",
            link: "https://www.ironhack.com/de-en",
            company: "Ironhack",
            location: "On site",
        },
        {
            key: 1,
            name: "Meta Front-End Developer",
            logo: "logos/coursera.svg",
            description:
                "Complete in August 2023. Learned the latest React best practices, straight from Meta themselves.",
            link: "https://coursera.org/verify/professional-cert/5GMTVUAPTVM2",
            company: "Coursera",
            location: "Remote",
        },
        {
            key: 2,
            name: "Responsive Web Design",
            logo: "logos/freecodecamp.svg",
            description:
                "Completed in April 2019. Specialized in creating responsive pages with HTML, CSS and Javascipt.",
            link: "https://www.freecodecamp.org/certification/benjaminelliott/responsive-web-design",
            company: "freecodecamp",
            location: "Remote",
        },
        {
            key: 3,
            name: "Legacy Javascript Algorithms & Data Structures",
            logo: "logos/freecodecamp.svg",
            description:
                "Completed in August 2023. Javascript algorithms and data sctuctures, specializing in using different data types and structures in Javascript ES6",
            link: "https://freecodecamp.org/certification/benjaminelliott/javascript-algorithms-and-data-structures",
            company: "freecodecamp",
            location: "Remote",
        },
    ],
    projects,
    technologies,
} as Benjamin;

export { benjamin };
